from . import roles
from . import usuarios
from . import categorias
from . import productos
from . import mesas
from . import pedidos
from . import detalle_pedido
from . import pagos
from . import ventas