"""Creacion inicial

Revision ID: 338b3e8a61f7
Revises: 
Create Date: 2026-07-05 21:37:31.542968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '338b3e8a61f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.alter_column('detalle_pedido', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detalle_pedido', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_detalle_pedido_id'), 'detalle_pedido', ['id'], unique=False)
    op.drop_constraint(op.f('fk_detalle_pedido'), 'detalle_pedido', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_pedido', 'pedidos', ['pedido_id'], ['id'])
    op.create_index(op.f('ix_mesas_id'), 'mesas', ['id'], unique=False)
    op.alter_column('pagos', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pagos', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.alter_column('pedidos', 'mesa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedidos', 'mesero_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedidos', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('usuarios', 'rol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.alter_column('ventas', 'pago_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ventas', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.alter_column('ventas', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ventas', 'pago_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.alter_column('usuarios', 'rol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.alter_column('pedidos', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pedidos', 'mesero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pedidos', 'mesa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.alter_column('pagos', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pagos', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_mesas_id'), table_name='mesas')
    op.drop_constraint(None, 'detalle_pedido', type_='foreignkey')
    op.create_foreign_key(op.f('fk_detalle_pedido'), 'detalle_pedido', 'pedidos', ['pedido_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_detalle_pedido_id'), table_name='detalle_pedido')
    op.alter_column('detalle_pedido', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detalle_pedido', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    # ### end Alembic commands ###
